[package]
name = "rest_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootstrap = {path = "./src/bootstrap"}
tokio = { version = "1.23.1", features = ["macros", "rt-multi-thread"] }